Product.create :name        => 'Big Bacon Bonanza', 
               :tip         => 'Try with Blue Cheese dipping sauce', 
               :category    => 'Pizza',
               :price       => 6.99,
               :description => 'Topped with bacon strips, bacon topping and four cheese blend. A bacon-lovers dream!'
Product.create :name        => 'Canadian Eh!', 
               :tip         => 'Try with Cheddar Jalapeno dipping sauce',
               :category    => 'Pizza',
               :price       => 8.99,
               :description => 'Topped with classic pepperoni, fresh mushrooms, bacon topping and mozzarella cheese.'
Product.create :name        => 'Tropical Hawaiian', 
               :tip         => 'Try this with a side order of chicken bites',
               :category    => 'Pizza',
               :price       => 7.99,
               :description => 'Topped with bacon topping, bacon strips, pineapple and mozzarella cheese.'
Product.create :name        => 'Pepperoni',
               :category    => 'Pizza',
               :price       => 4.99
